# Site settings
title: "Semantest - AI-Powered Browser Testing"
description: "Write browser tests like you'd explain them to a colleague. Natural language testing that actually works."
tagline: "Browser testing that speaks your language"
baseurl: ""
url: "https://semantest.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: minima

# Collections for modules and documentation
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /guides/:name/
  api:
    output: true
    permalink: /api/:name/
  tutorials:
    output: true
    permalink: /tutorials/:name/
  success-stories:
    output: true
    permalink: /success-stories/:name/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - getting-started/README.md
  - tutorials/real-world-amazon-testing.md
  - api-reference.md
  - success-stories/README.md
  - examples.md

# Custom navigation menu
navigation:
  - title: "Getting Started"
    url: "/getting-started/"
  - title: "Tutorials"
    url: "/tutorials/"
  - title: "API Reference"
    url: "/api/"
  - title: "Success Stories"
    url: "/success-stories/"
  - title: "GitHub"
    url: "https://github.com/semantest/semantest"
  - title: "Discord"
    url: "https://discord.gg/semantest"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.tgz"
  - "package*.json"
  - "tsconfig*.json"
  - "jest.config.js"
  - "playwright.config.ts"

# Include
include:
  - _pages

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"

# SEO and Social
author: Semantest Team
github_username: semantest
twitter_username: semantest
logo: /assets/semantest-logo.png

# SEO tags
twitter:
  card: summary_large_image
  username: semantest
  
social:
  name: Semantest
  links:
    - https://twitter.com/semantest
    - https://github.com/semantest
    - https://discord.gg/semantest

# Google Analytics (add when ready)
# google_analytics: UA-XXXXXXXXX

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Sass
sass:
  style: compressed