# Site settings
title: "Semantest Ecosystem"
description: "AI-driven automation tools for modern web development"
baseurl: ""
url: "https://semantest.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections for each project
collections:
  typescript-eda:
    output: true
    permalink: /:collection/:name/
  semantest:
    output: true
    permalink: /:collection/:name/
  semantest-chatgpt:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Default layouts
defaults:
  - scope:
      path: ""
      type: "typescript-eda"
    values:
      layout: "project"
      project: "typescript-eda"
  - scope:
      path: ""
      type: "semantest"
    values:
      layout: "project"
      project: "semantest"
  - scope:
      path: ""
      type: "semantest-chatgpt"
    values:
      layout: "project"
      project: "semantest-chatgpt"

# Site navigation
nav_links:
  - title: "TypeScript-EDA"
    url: "/typescript-eda/"
    description: "Core EDA framework"
  - title: "Semantest" 
    url: "/semantest/"
    description: "AI automation framework"
  - title: "ChatGPT Integration"
    url: "/semantest-chatgpt/"
    description: "ChatGPT automation"

# Project metadata
projects:
  typescript-eda:
    name: "TypeScript-EDA"
    description: "Event-driven architecture framework"
    icon: "🏗️"
    github: "https://github.com/typescript-eda/domain"
    npm: "@typescript-eda/core"
  semantest:
    name: "Semantest"
    description: "AI-driven web automation framework"
    icon: "🤖"
    github: "https://github.com/semantest/semantest"
    npm: "@semantest/browser"
  semantest-chatgpt:
    name: "Semantest ChatGPT"
    description: "ChatGPT automation specialist"
    icon: "💬"
    github: "https://github.com/semantest/semantest"
    npm: "@semantest/chatgpt.com"