# Site settings
title: "Semantest Framework"
description: "Advanced browser automation and semantic testing platform with TypeScript-EDA architecture"
baseurl: ""
url: "https://semantest.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: minima

# Collections for modules and documentation
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /guides/:name/
  api:
    output: true
    permalink: /api/:name/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - getting-started.md
  - architecture.md
  - api-reference.md
  - examples.md

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.tgz"
  - "package*.json"
  - "tsconfig*.json"
  - "jest.config.js"
  - "playwright.config.ts"

# Include
include:
  - _pages

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"

# SEO
author: Semantest Team
github_username: semantest

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Sass
sass:
  style: compressed